about:
    path:     about
    defaults: { _controller: AppBundle:OtherPages:showAbout }

legal_mentions:
    path:     legalMentions
    defaults: { _controller: AppBundle:OtherPages:showLegalMentions }
    
accueil:
    path:     /
    defaults: { _controller: AppBundle:OtherPages:index }
